// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMTbBZd92aoKpvceUbQ0_BZfRolHLzgoU',
    appId: '1:404494923847:web:a544ac9468c9588bd31962',
    messagingSenderId: '404494923847',
    projectId: 'weather-website-e28f5',
    authDomain: 'weather-website-e28f5.firebaseapp.com',
    storageBucket: 'weather-website-e28f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYrC965Bm-YLZx1DFumx1jdjuG5fE4X8',
    appId: '1:404494923847:android:f739fcbde381ff04d31962',
    messagingSenderId: '404494923847',
    projectId: 'weather-website-e28f5',
    storageBucket: 'weather-website-e28f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq25KR6hE8CKaYXbT2Nje3q1qNDexMlE0',
    appId: '1:404494923847:ios:6002ee6d7f3218a8d31962',
    messagingSenderId: '404494923847',
    projectId: 'weather-website-e28f5',
    storageBucket: 'weather-website-e28f5.firebasestorage.app',
    iosBundleId: 'com.example.gweatherforecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq25KR6hE8CKaYXbT2Nje3q1qNDexMlE0',
    appId: '1:404494923847:ios:6002ee6d7f3218a8d31962',
    messagingSenderId: '404494923847',
    projectId: 'weather-website-e28f5',
    storageBucket: 'weather-website-e28f5.firebasestorage.app',
    iosBundleId: 'com.example.gweatherforecast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMTbBZd92aoKpvceUbQ0_BZfRolHLzgoU',
    appId: '1:404494923847:web:11bc2452d037ffd4d31962',
    messagingSenderId: '404494923847',
    projectId: 'weather-website-e28f5',
    authDomain: 'weather-website-e28f5.firebaseapp.com',
    storageBucket: 'weather-website-e28f5.firebasestorage.app',
  );
}
